apiVersion: v1
kind: Service
metadata:
  name: deployment-nodeport-service
spec:
  type: NodePort
  selector:
    app: myapp3
  ports:
    - name: http
      targetPort: 80
      port: 80
      nodePort: 31323