apiVersion: v1
kind: Service
metadata:
  name: myapp-pod-nodeport-dervice
  labels:
    app: myapp-svc

spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31231

