apiVersion: v1
kind: Service
metadata:
  name: replicaset-nodeport-svc
spec:
  type: NodePort
  selector:
    app: myapp2
  ports: 
    - name: http
      targetPort: 80
      port: 80
      nodePort: 31322
      