apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-microservice-v2
  labels:
    app: notification-restapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-restapp
  template:
    metadata:
      labels:
        app: notification-restapp
    spec:
      containers:
        - name: notification-service
          image: stacksimplify/kube-notifications-microservice:4.0.0-AWS-XRay
          ports:
            - containerPort: 8096
          imagePullPolicy: Always
          env:
            - name: AWS_MAIL_SERVER_HOST
              value: "ms-smtp-service"
            - name: AWS_MAIL_SERVER_USERNAME
              value: "AKIAVHNKUZGIDXE4OU4D"
            - name: AWS_MAIL_SERVER_PASSWORD
              value: "BI6+MdbhH6L+mD8+2he/cjCFujfPYpJ2Owd78xhKhJoU"
            - name: AWS_MAIL_SERVER_FROM_ADDRESS
              value: "surekye@gmail.com"
            - name: AWS_XRAY_TRACING_NAME 
              value: "V2-Notification-Microservice"              
            - name: AWS_XRAY_DAEMON_ADDRESS
              value: "xray-service.default:2000"      
            - name: AWS_XRAY_CONTEXT_MISSING 
              value: "LOG_ERROR"  # Log an error and continue, Ideally RUNTIME_ERROR – Throw a runtime exception which is default option if not configured 