apiVersion: v1
kind: Service
metadata:
  name: usermgmt-restapp-nlb
  labels: 
    app: usermgmt-restapp
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb

spec: 
  type: LoadBalancer
  selector: 
    app: usermgmt-restapp
  ports:
    - targetPort: 8095
      port: 80
