apiVersion: v1
kind: Service
metadata:
  name: usermgmt-restapp-clb
  labels: 
    app: usermgmt-restapp

spec: 
  type: LoadBalancer
  selector: 
    app: usermgmt-restapp
  ports:
    - targetPort: 8095
      port: 80
