apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-microservice
  labels:
    app: notification-restapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-restapp
  template:
    metadata:
      labels:
        app: notification-restapp
    spec:
      containers:
        - name: notification-service
          image: stacksimplify/kube-notifications-microservice:2.0.0
          ports:
            - containerPort: 8096
          imagePullPolicy: Always
          env:
            - name: AWS_MAIL_SERVER_HOST
              value: "ms-smtp-service"
            - name: AWS_MAIL_SERVER_USERNAME
              value: "AKIAVHNKUZGIDXE4OU4D"
            - name: AWS_MAIL_SERVER_PASSWORD
              value: "BI6+MdbhH6L+mD8+2he/cjCFujfPYpJ2Owd78xhKhJoU"
            - name: AWS_MAIL_SERVER_FROM_ADDRESS
              value: "surekye@gmail.com"